use_frameworks!

target 'RTCreditCardInput_Example' do
  pod 'RTCreditCardInput', :path => '../'

  target 'RTCreditCardInput_Tests' do
    inherit! :search_paths

    
  end
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
